/* Generated By:CSharpCC: Do not edit this line. GRSImporterConstants.cs */
namespace de.unika.ipd.grGen.libGr.porter{
public class GRSImporterConstants {

  internal const int EOF = 0;
  internal const int NL = 7;
  internal const int QUOTE = 8;
  internal const int SINGLEQUOTE = 9;
  internal const int DOUBLECOLON = 10;
  internal const int EQUAL = 11;
  internal const int COMMA = 12;
  internal const int ARROW = 13;
  internal const int MINUS = 14;
  internal const int LPARENTHESIS = 15;
  internal const int RPARENTHESIS = 16;
  internal const int AT = 17;
  internal const int LANGLE = 18;
  internal const int RANGLE = 19;
  internal const int LBRACE = 20;
  internal const int RBRACE = 21;
  internal const int LBOXBRACKET = 22;
  internal const int RBOXBRACKET = 23;
  internal const int FALSE = 24;
  internal const int GRAPH = 25;
  internal const int NEW = 26;
  internal const int NODE = 27;
  internal const int NULL = 28;
  internal const int TRUE = 29;
  internal const int SET = 30;
  internal const int MAP = 31;
  internal const int ARRAY = 32;
  internal const int NUMBER = 33;
  internal const int NUMBER_BYTE = 34;
  internal const int NUMBER_SHORT = 35;
  internal const int NUMBER_LONG = 36;
  internal const int HEXNUMBER = 37;
  internal const int HEXNUMBER_BYTE = 38;
  internal const int HEXNUMBER_SHORT = 39;
  internal const int HEXNUMBER_LONG = 40;
  internal const int NUMFLOAT = 41;
  internal const int NUMDOUBLE = 42;
  internal const int EXPONENT = 43;
  internal const int DOUBLEQUOTEDTEXT = 44;
  internal const int SINGLEQUOTEDTEXT = 45;
  internal const int WORD = 46;
  internal const int SINGLE_LINE_COMMENT = 47;
  internal const int DOUBLEQUOTEDFILENAME = 51;
  internal const int SINGLEQUOTEDFILENAME = 52;
  internal const int FILENAME = 53;
  internal const int NLINFILENAME = 54;
  internal const int ERRORFILENAME = 55;

  internal const int DEFAULT = 0;
  internal const int WithinFilename = 1;

  internal readonly string[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\\\\\r\\n\"",
    "\"\\\\\\n\"",
    "\"\\\\\\r\"",
    "\"\\n\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"::\"",
    "\"=\"",
    "\",\"",
    "\"->\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "\"@\"",
    "\"<\"",
    "\">\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"false\"",
    "\"graph\"",
    "\"new\"",
    "\"node\"",
    "\"null\"",
    "\"true\"",
    "\"set\"",
    "\"map\"",
    "\"array\"",
    "<NUMBER>",
    "<NUMBER_BYTE>",
    "<NUMBER_SHORT>",
    "<NUMBER_LONG>",
    "<HEXNUMBER>",
    "<HEXNUMBER_BYTE>",
    "<HEXNUMBER_SHORT>",
    "<HEXNUMBER_LONG>",
    "<NUMFLOAT>",
    "<NUMDOUBLE>",
    "<EXPONENT>",
    "<DOUBLEQUOTEDTEXT>",
    "<SINGLEQUOTEDTEXT>",
    "<WORD>",
    "<SINGLE_LINE_COMMENT>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<DOUBLEQUOTEDFILENAME>",
    "<SINGLEQUOTEDFILENAME>",
    "<FILENAME>",
    "\"\\n\"",
    "<ERRORFILENAME>",
    "\".\"",
    "\":\"",
    "\"$\"",
  };

}
}
