/* Generated By:CSharpCC: Do not edit this line. GrShellConstants.cs */
namespace de.unika.ipd.grGen.grShell{
public class GrShellConstants {

  internal const int EOF = 0;
  internal const int NL = 7;
  internal const int QUOTE = 8;
  internal const int SINGLEQUOTE = 9;
  internal const int DOUBLECOLON = 10;
  internal const int COLON = 11;
  internal const int DOUBLESEMICOLON = 12;
  internal const int SEMICOLON = 13;
  internal const int EQUAL = 14;
  internal const int DOT = 15;
  internal const int COMMA = 16;
  internal const int DOLLAR = 17;
  internal const int DOUBLEAMPERSAND = 18;
  internal const int AMPERSAND = 19;
  internal const int DOUBLEPIPE = 20;
  internal const int PIPE = 21;
  internal const int CIRCUMFLEX = 22;
  internal const int ARROW = 23;
  internal const int MINUS = 24;
  internal const int STAR = 25;
  internal const int PLUS = 26;
  internal const int EXCLAMATIONMARK = 27;
  internal const int QUESTIONMARK = 28;
  internal const int PERCENT = 29;
  internal const int LPARENTHESIS = 30;
  internal const int RPARENTHESIS = 31;
  internal const int LBRACE = 32;
  internal const int RBRACE = 33;
  internal const int LBOXBRACKET = 34;
  internal const int RBOXBRACKET = 35;
  internal const int LANGLE = 36;
  internal const int RANGLE = 37;
  internal const int AT = 38;
  internal const int ACTIONS = 39;
  internal const int ADD = 40;
  internal const int APPLY = 41;
  internal const int ARRAY = 42;
  internal const int ASKFOR = 43;
  internal const int ATTRIBUTES = 44;
  internal const int BACKEND = 45;
  internal const int BORDERCOLOR = 46;
  internal const int BY = 47;
  internal const int CD = 48;
  internal const int CLEAR = 49;
  internal const int COLOR = 50;
  internal const int CUSTOM = 51;
  internal const int DEBUG = 52;
  internal const int DEF = 53;
  internal const int DELETE = 54;
  internal const int DISABLE = 55;
  internal const int DUMP = 56;
  internal const int ECHO = 57;
  internal const int EDGE = 58;
  internal const int EDGES = 59;
  internal const int EMIT = 60;
  internal const int ENABLE = 61;
  internal const int EXCLUDE = 62;
  internal const int EXEC = 63;
  internal const int EXIT = 64;
  internal const int EXITONFAILURE = 65;
  internal const int EXPORT = 66;
  internal const int FALSE = 67;
  internal const int FILE = 68;
  internal const int FROM = 69;
  internal const int GET = 70;
  internal const int GRAPH = 71;
  internal const int GRAPHS = 72;
  internal const int GROUP = 73;
  internal const int GRS = 74;
  internal const int HELP = 75;
  internal const int HIDDEN = 76;
  internal const int IMPORT = 77;
  internal const int INCLUDE = 78;
  internal const int INFOTAG = 79;
  internal const int IO = 80;
  internal const int IS = 81;
  internal const int KEEPDEBUG = 82;
  internal const int LABELS = 83;
  internal const int LAYOUT = 84;
  internal const int LAZYNIC = 85;
  internal const int LS = 86;
  internal const int MAP = 87;
  internal const int MODE = 88;
  internal const int NEW = 89;
  internal const int NODE = 90;
  internal const int NODES = 91;
  internal const int NULL = 92;
  internal const int NUM = 93;
  internal const int OFF = 94;
  internal const int ON = 95;
  internal const int ONLY = 96;
  internal const int OPEN = 97;
  internal const int OPTION = 98;
  internal const int OPTIONS = 99;
  internal const int PARSE = 100;
  internal const int PARSER = 101;
  internal const int PWD = 102;
  internal const int QUIT = 103;
  internal const int RANDOMSEED = 104;
  internal const int RECORD = 105;
  internal const int REDIRECT = 106;
  internal const int REFERENCE = 107;
  internal const int REM = 108;
  internal const int REPLAY = 109;
  internal const int RESET = 110;
  internal const int RETYPE = 111;
  internal const int SAVE = 112;
  internal const int SELECT = 113;
  internal const int SET = 114;
  internal const int SHAPE = 115;
  internal const int SHORTINFOTAG = 116;
  internal const int SHOW = 117;
  internal const int SILENCE = 118;
  internal const int SPECIFIED = 119;
  internal const int START = 120;
  internal const int STRICT = 121;
  internal const int STOP = 122;
  internal const int LINESTYLE = 123;
  internal const int SUB = 124;
  internal const int SUPER = 125;
  internal const int SYNC = 126;
  internal const int TEXTCOLOR = 127;
  internal const int THICKNESS = 128;
  internal const int TO = 129;
  internal const int TRUE = 130;
  internal const int TYPE = 131;
  internal const int TYPES = 132;
  internal const int VALIDATE = 133;
  internal const int VAR = 134;
  internal const int WITH = 135;
  internal const int XGRS = 136;
  internal const int NUMBER = 137;
  internal const int NUMBER_BYTE = 138;
  internal const int NUMBER_SHORT = 139;
  internal const int NUMBER_LONG = 140;
  internal const int HEXNUMBER = 141;
  internal const int HEXNUMBER_BYTE = 142;
  internal const int HEXNUMBER_SHORT = 143;
  internal const int HEXNUMBER_LONG = 144;
  internal const int NUMFLOAT = 145;
  internal const int NUMDOUBLE = 146;
  internal const int EXPONENT = 147;
  internal const int DOUBLEQUOTEDTEXT = 148;
  internal const int SINGLEQUOTEDTEXT = 149;
  internal const int WORD = 150;
  internal const int SINGLE_LINE_COMMENT = 151;
  internal const int DOUBLEQUOTEDFILENAME = 155;
  internal const int SINGLEQUOTEDFILENAME = 156;
  internal const int FILENAME = 157;
  internal const int NLINFILENAME = 158;
  internal const int ERRORFILENAME = 159;
  internal const int COMMANDLINE = 160;
  internal const int DOUBLEQUOTEDANYSTRING = 164;
  internal const int SINGLEQUOTEDANYSTRING = 165;
  internal const int ANYSTRING = 166;
  internal const int ERRORANYSTRING = 167;
  internal const int DOUBLEQUOTEDATTRIBUTENAME = 168;
  internal const int SINGLEQUOTEDATTRIBUTENAME = 169;
  internal const int ATTRIBUTENAME = 170;
  internal const int ERRORATTRIBUTENAME = 171;
  internal const int DOUBLEQUOTEDANYSTRINGS = 178;
  internal const int SINGLEQUOTEDANYSTRINGS = 179;
  internal const int ANYSTRINGS = 180;
  internal const int NLINANYSTRINGS = 181;
  internal const int ERRORANYSTRINGS = 182;
  internal const int ERROR = 184;

  internal const int DEFAULT = 0;
  internal const int WithinFilename = 1;
  internal const int WithinCommand = 2;
  internal const int WithinAnyString = 3;
  internal const int WithinAttributeName = 4;
  internal const int WithinAnyStrings = 5;

  internal readonly string[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\\\\\r\\n\"",
    "\"\\\\\\n\"",
    "\"\\\\\\r\"",
    "\"\\n\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"::\"",
    "\":\"",
    "\";;\"",
    "\";\"",
    "\"=\"",
    "\".\"",
    "\",\"",
    "\"$\"",
    "\"&&\"",
    "\"&\"",
    "\"||\"",
    "\"|\"",
    "\"^\"",
    "\"->\"",
    "\"-\"",
    "\"*\"",
    "\"+\"",
    "\"!\"",
    "\"?\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"<\"",
    "\">\"",
    "\"@\"",
    "\"actions\"",
    "\"add\"",
    "\"apply\"",
    "\"array\"",
    "\"askfor\"",
    "\"attributes\"",
    "\"backend\"",
    "\"bordercolor\"",
    "\"by\"",
    "\"cd\"",
    "\"clear\"",
    "\"color\"",
    "\"custom\"",
    "\"debug\"",
    "\"def\"",
    "\"delete\"",
    "\"disable\"",
    "\"dump\"",
    "\"echo\"",
    "\"edge\"",
    "\"edges\"",
    "\"emit\"",
    "\"enable\"",
    "\"exclude\"",
    "\"exec\"",
    "\"exit\"",
    "\"exitonfailure\"",
    "\"export\"",
    "\"false\"",
    "\"file\"",
    "\"from\"",
    "\"get\"",
    "\"graph\"",
    "\"graphs\"",
    "\"group\"",
    "\"grs\"",
    "\"help\"",
    "\"hidden\"",
    "\"import\"",
    "\"include\"",
    "\"infotag\"",
    "\"io\"",
    "\"is\"",
    "\"keepdebug\"",
    "\"labels\"",
    "\"layout\"",
    "\"lazynic\"",
    "\"ls\"",
    "\"map\"",
    "\"mode\"",
    "\"new\"",
    "\"node\"",
    "\"nodes\"",
    "\"null\"",
    "\"num\"",
    "\"off\"",
    "\"on\"",
    "\"only\"",
    "\"open\"",
    "\"option\"",
    "\"options\"",
    "\"parse\"",
    "\"parser\"",
    "\"pwd\"",
    "\"quit\"",
    "\"randomseed\"",
    "\"record\"",
    "\"redirect\"",
    "\"reference\"",
    "\"rem\"",
    "\"replay\"",
    "\"reset\"",
    "\"retype\"",
    "\"save\"",
    "\"select\"",
    "\"set\"",
    "\"shape\"",
    "\"shortinfotag\"",
    "\"show\"",
    "\"silence\"",
    "\"specified\"",
    "\"start\"",
    "\"strict\"",
    "\"stop\"",
    "\"linestyle\"",
    "\"sub\"",
    "\"super\"",
    "\"sync\"",
    "\"textcolor\"",
    "\"thickness\"",
    "\"to\"",
    "\"true\"",
    "\"type\"",
    "\"types\"",
    "\"validate\"",
    "\"var\"",
    "\"with\"",
    "\"xgrs\"",
    "<NUMBER>",
    "<NUMBER_BYTE>",
    "<NUMBER_SHORT>",
    "<NUMBER_LONG>",
    "<HEXNUMBER>",
    "<HEXNUMBER_BYTE>",
    "<HEXNUMBER_SHORT>",
    "<HEXNUMBER_LONG>",
    "<NUMFLOAT>",
    "<NUMDOUBLE>",
    "<EXPONENT>",
    "<DOUBLEQUOTEDTEXT>",
    "<SINGLEQUOTEDTEXT>",
    "<WORD>",
    "<SINGLE_LINE_COMMENT>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<DOUBLEQUOTEDFILENAME>",
    "<SINGLEQUOTEDFILENAME>",
    "<FILENAME>",
    "\"\\n\"",
    "<ERRORFILENAME>",
    "<COMMANDLINE>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<DOUBLEQUOTEDANYSTRING>",
    "<SINGLEQUOTEDANYSTRING>",
    "<ANYSTRING>",
    "<ERRORANYSTRING>",
    "<DOUBLEQUOTEDATTRIBUTENAME>",
    "<SINGLEQUOTEDATTRIBUTENAME>",
    "<ATTRIBUTENAME>",
    "<ERRORATTRIBUTENAME>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\\\\\r\\n\"",
    "\"\\\\\\n\"",
    "\"\\\\\\r\"",
    "<DOUBLEQUOTEDANYSTRINGS>",
    "<SINGLEQUOTEDANYSTRINGS>",
    "<ANYSTRINGS>",
    "\"\\n\"",
    "<ERRORANYSTRINGS>",
    "\"<-\"",
    "<ERROR>",
  };

}
}
